"""Master list of listed Indian defence companies with metadata."""

DEFENCE_COMPANIES = [
    {
        "name": "MTAR Technologies",
        "short": "MTAR",
        "ticker": "MTARTECH.NS",
        "bse_code": "543270",
        "sector": "Aerospace & Defence",
        "sub_sector": "Precision Engineering",
        "description": "High-precision components for defence, space (ISRO) and nuclear programmes.",
    },
    {
        "name": "Data Patterns (India) Limited",
        "short": "DATAPATTNS",
        "ticker": "DATAPATTNS.NS",
        "bse_code": "543428",
        "sector": "Aerospace & Defence",
        "sub_sector": "Defence Electronics",
        "description": "Vertically integrated defence electronics firm; radar and avionics subsystems.",
    },
    {
        "name": "Azad Engineering Limited",
        "short": "AZAD",
        "ticker": "AZAD.NS",
        "bse_code": "544133",
        "sector": "Aerospace & Defence",
        "sub_sector": "Precision Engineering",
        "description": "High-precision complex components for aerospace, defence, energy and oil & gas sectors.",
    },
    {
        "name": "Zen Technologies Limited",
        "short": "ZENTEC",
        "ticker": "ZENTEC.NS",
        "bse_code": "533339",
        "sector": "Aerospace & Defence",
        "sub_sector": "Training Simulators",
        "description": "Combat training simulators and anti-drone solutions for armed forces.",
    },
    {
        "name": "Ideaforge Technology",
        "short": "IDEAFORGE",
        "ticker": "IDEAFORGE.NS",
        "bse_code": "543932",
        "sector": "Aerospace & Defence",
        "sub_sector": "Drones & UAVs",
        "description": "India's leading UAV / drone manufacturer for defence and surveillance.",
    },
    {
        "name": "Paras Defence and Space Technologies",
        "short": "PARASDEF",
        "ticker": "PARASDEFE.NS",
        "bse_code": "543367",
        "sector": "Aerospace & Defence",
        "sub_sector": "Defence Optics & EMP",
        "description": "Defence optics, electro-optics, EMP protection and space technology.",
    },
    {
        "name": "Aequs Aerospace",
        "short": "AEQUS",
        "ticker": "AEQUS.NS",
        "bse_code": "",
        "sector": "Aerospace & Defence",
        "sub_sector": "Precision Engineering",
        "description": "Integrated aerospace supply chain — machining, casting, assemblies for global OEMs.",
    },
    {
        "name": "Astra Microwave Products",
        "short": "ASTRAMICRO",
        "ticker": "ASTRAMICRO.NS",
        "bse_code": "532493",
        "sector": "Aerospace & Defence",
        "sub_sector": "RF & Microwave Systems",
        "description": "Designs RF and microwave subsystems for missile, radar and EW applications.",
    },
]

SECTOR_COLORS = {
    "Aircraft Manufacturing": "#1a237e",
    "Defence Electronics":    "#283593",
    "Defence Vehicles & Mining": "#303f9f",
    "Missiles & Torpedoes":   "#3949ab",
    "Shipbuilding":           "#1565c0",
    "Defence Optics & EMP":   "#0277bd",
    "RF & Microwave Systems": "#00838f",
    "Precision Engineering":  "#00695c",
    "Explosives & Ammunition":"#2e7d32",
    "Training Simulators":    "#558b2f",
    "Cable Harness & Systems":"#f57f17",
    "Drones & UAVs":          "#e65100",
}
